version: '2'
services:
    apichallenge-app:
        image: apichallenge
        external_links:
            - apichallenge-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/apichallenge?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    apichallenge-mysql:
        extends:
            file: mysql.yml
            service: apichallenge-mysql
